from distutils.core import setup

setup(
    name='PyInvestment',
    version='0.0.0.1',
    packages=['', 'lib.python3.5.distutils', 'lib.python3.5.encodings', 'lib.python3.5.importlib',
              'lib.python3.5.collections', 'lib.python3.5.site-packages.py', 'lib.python3.5.site-packages.py._io',
              'lib.python3.5.site-packages.py._log', 'lib.python3.5.site-packages.py._code',
              'lib.python3.5.site-packages.py._path', 'lib.python3.5.site-packages.py._process',
              'lib.python3.5.site-packages.bs4', 'lib.python3.5.site-packages.bs4.tests',
              'lib.python3.5.site-packages.bs4.builder', 'lib.python3.5.site-packages.pip',
              'lib.python3.5.site-packages.pip.req', 'lib.python3.5.site-packages.pip.vcs',
              'lib.python3.5.site-packages.pip.utils', 'lib.python3.5.site-packages.pip.compat',
              'lib.python3.5.site-packages.pip.models', 'lib.python3.5.site-packages.pip._vendor',
              'lib.python3.5.site-packages.pip._vendor.distlib',
              'lib.python3.5.site-packages.pip._vendor.distlib._backport',
              'lib.python3.5.site-packages.pip._vendor.colorama', 'lib.python3.5.site-packages.pip._vendor.html5lib',
              'lib.python3.5.site-packages.pip._vendor.html5lib._trie',
              'lib.python3.5.site-packages.pip._vendor.html5lib.filters',
              'lib.python3.5.site-packages.pip._vendor.html5lib.treewalkers',
              'lib.python3.5.site-packages.pip._vendor.html5lib.treeadapters',
              'lib.python3.5.site-packages.pip._vendor.html5lib.treebuilders',
              'lib.python3.5.site-packages.pip._vendor.lockfile', 'lib.python3.5.site-packages.pip._vendor.progress',
              'lib.python3.5.site-packages.pip._vendor.requests',
              'lib.python3.5.site-packages.pip._vendor.requests.packages',
              'lib.python3.5.site-packages.pip._vendor.requests.packages.chardet',
              'lib.python3.5.site-packages.pip._vendor.requests.packages.urllib3',
              'lib.python3.5.site-packages.pip._vendor.requests.packages.urllib3.util',
              'lib.python3.5.site-packages.pip._vendor.requests.packages.urllib3.contrib',
              'lib.python3.5.site-packages.pip._vendor.requests.packages.urllib3.packages',
              'lib.python3.5.site-packages.pip._vendor.requests.packages.urllib3.packages.ssl_match_hostname',
              'lib.python3.5.site-packages.pip._vendor.packaging',
              'lib.python3.5.site-packages.pip._vendor.cachecontrol',
              'lib.python3.5.site-packages.pip._vendor.cachecontrol.caches',
              'lib.python3.5.site-packages.pip._vendor.webencodings',
              'lib.python3.5.site-packages.pip._vendor.pkg_resources', 'lib.python3.5.site-packages.pip.commands',
              'lib.python3.5.site-packages.pip.operations', 'lib.python3.5.site-packages.attr',
              'lib.python3.5.site-packages.cffi', 'lib.python3.5.site-packages.idna',
              'lib.python3.5.site-packages.lxml', 'lib.python3.5.site-packages.lxml.html',
              'lib.python3.5.site-packages.lxml.includes', 'lib.python3.5.site-packages.lxml.isoschematron',
              'lib.python3.5.site-packages.pytz', 'lib.python3.5.site-packages.zope.interface',
              'lib.python3.5.site-packages.zope.interface.tests', 'lib.python3.5.site-packages.zope.interface.common',
              'lib.python3.5.site-packages.zope.interface.common.tests', 'lib.python3.5.site-packages.numpy',
              'lib.python3.5.site-packages.numpy.ma', 'lib.python3.5.site-packages.numpy.doc',
              'lib.python3.5.site-packages.numpy.fft', 'lib.python3.5.site-packages.numpy.lib',
              'lib.python3.5.site-packages.numpy.core', 'lib.python3.5.site-packages.numpy.f2py',
              'lib.python3.5.site-packages.numpy.compat', 'lib.python3.5.site-packages.numpy.linalg',
              'lib.python3.5.site-packages.numpy.random', 'lib.python3.5.site-packages.numpy.testing',
              'lib.python3.5.site-packages.numpy.distutils', 'lib.python3.5.site-packages.numpy.distutils.command',
              'lib.python3.5.site-packages.numpy.distutils.fcompiler', 'lib.python3.5.site-packages.numpy.matrixlib',
              'lib.python3.5.site-packages.numpy.polynomial', 'lib.python3.5.site-packages.w3lib',
              'lib.python3.5.site-packages.wheel', 'lib.python3.5.site-packages.wheel.test',
              'lib.python3.5.site-packages.wheel.test.simple.dist.simpledist',
              'lib.python3.5.site-packages.wheel.test.complex-dist.complexdist',
              'lib.python3.5.site-packages.wheel.tool', 'lib.python3.5.site-packages.wheel.signatures',
              'lib.python3.5.site-packages.pandas', 'lib.python3.5.site-packages.pandas.io',
              'lib.python3.5.site-packages.pandas.io.sas', 'lib.python3.5.site-packages.pandas.io.tests',
              'lib.python3.5.site-packages.pandas.io.tests.json', 'lib.python3.5.site-packages.pandas.io.tests.parser',
              'lib.python3.5.site-packages.pandas.api', 'lib.python3.5.site-packages.pandas.api.tests',
              'lib.python3.5.site-packages.pandas.api.types', 'lib.python3.5.site-packages.pandas.rpy',
              'lib.python3.5.site-packages.pandas.core', 'lib.python3.5.site-packages.pandas.util',
              'lib.python3.5.site-packages.pandas.stats', 'lib.python3.5.site-packages.pandas.stats.tests',
              'lib.python3.5.site-packages.pandas.tests', 'lib.python3.5.site-packages.pandas.tests.frame',
              'lib.python3.5.site-packages.pandas.tests.types', 'lib.python3.5.site-packages.pandas.tests.series',
              'lib.python3.5.site-packages.pandas.tests.formats', 'lib.python3.5.site-packages.pandas.tests.indexes',
              'lib.python3.5.site-packages.pandas.tests.plotting',
              'lib.python3.5.site-packages.pandas.tests.test_msgpack', 'lib.python3.5.site-packages.pandas.tools',
              'lib.python3.5.site-packages.pandas.tools.tests', 'lib.python3.5.site-packages.pandas.types',
              'lib.python3.5.site-packages.pandas.compat', 'lib.python3.5.site-packages.pandas.compat.numpy',
              'lib.python3.5.site-packages.pandas.sparse', 'lib.python3.5.site-packages.pandas.sparse.tests',
              'lib.python3.5.site-packages.pandas.formats', 'lib.python3.5.site-packages.pandas.indexes',
              'lib.python3.5.site-packages.pandas.msgpack', 'lib.python3.5.site-packages.pandas.tseries',
              'lib.python3.5.site-packages.pandas.tseries.tests', 'lib.python3.5.site-packages.pandas.computation',
              'lib.python3.5.site-packages.pandas.computation.tests', 'lib.python3.5.site-packages.parsel',
              'lib.python3.5.site-packages.pyasn1', 'lib.python3.5.site-packages.pyasn1.type',
              'lib.python3.5.site-packages.pyasn1.codec', 'lib.python3.5.site-packages.pyasn1.codec.ber',
              'lib.python3.5.site-packages.pyasn1.codec.cer', 'lib.python3.5.site-packages.pyasn1.codec.der',
              'lib.python3.5.site-packages.pyasn1.compat', 'lib.python3.5.site-packages.scrapy',
              'lib.python3.5.site-packages.scrapy.core', 'lib.python3.5.site-packages.scrapy.core.downloader',
              'lib.python3.5.site-packages.scrapy.core.downloader.handlers', 'lib.python3.5.site-packages.scrapy.http',
              'lib.python3.5.site-packages.scrapy.http.request', 'lib.python3.5.site-packages.scrapy.http.response',
              'lib.python3.5.site-packages.scrapy.xlib', 'lib.python3.5.site-packages.scrapy.xlib.tx',
              'lib.python3.5.site-packages.scrapy.utils', 'lib.python3.5.site-packages.scrapy.loader',
              'lib.python3.5.site-packages.scrapy.contrib', 'lib.python3.5.site-packages.scrapy.contrib.loader',
              'lib.python3.5.site-packages.scrapy.contrib.spiders',
              'lib.python3.5.site-packages.scrapy.contrib.exporter',
              'lib.python3.5.site-packages.scrapy.contrib.pipeline',
              'lib.python3.5.site-packages.scrapy.contrib.linkextractors',
              'lib.python3.5.site-packages.scrapy.contrib.spidermiddleware',
              'lib.python3.5.site-packages.scrapy.contrib.downloadermiddleware',
              'lib.python3.5.site-packages.scrapy.spiders', 'lib.python3.5.site-packages.scrapy.commands',
              'lib.python3.5.site-packages.scrapy.selector', 'lib.python3.5.site-packages.scrapy.settings',
              'lib.python3.5.site-packages.scrapy.contracts', 'lib.python3.5.site-packages.scrapy.pipelines',
              'lib.python3.5.site-packages.scrapy.templates.project.module',
              'lib.python3.5.site-packages.scrapy.templates.project.module.spiders',
              'lib.python3.5.site-packages.scrapy.extensions', 'lib.python3.5.site-packages.scrapy.contrib_exp',
              'lib.python3.5.site-packages.scrapy.contrib_exp.downloadermiddleware',
              'lib.python3.5.site-packages.scrapy.linkextractors',
              'lib.python3.5.site-packages.scrapy.spidermiddlewares',
              'lib.python3.5.site-packages.scrapy.downloadermiddlewares', 'lib.python3.5.site-packages.OpenSSL',
              'lib.python3.5.site-packages._pytest', 'lib.python3.5.site-packages._pytest._code',
              'lib.python3.5.site-packages._pytest.assertion', 'lib.python3.5.site-packages._pytest.vendored_packages',
              'lib.python3.5.site-packages.quantpy', 'lib.python3.5.site-packages.twisted',
              'lib.python3.5.site-packages.twisted.web', 'lib.python3.5.site-packages.twisted.web.test',
              'lib.python3.5.site-packages.twisted.web._auth', 'lib.python3.5.site-packages.twisted.cred',
              'lib.python3.5.site-packages.twisted.cred.test', 'lib.python3.5.site-packages.twisted.pair',
              'lib.python3.5.site-packages.twisted.pair.test', 'lib.python3.5.site-packages.twisted.test',
              'lib.python3.5.site-packages.twisted.conch', 'lib.python3.5.site-packages.twisted.conch.ssh',
              'lib.python3.5.site-packages.twisted.conch.test', 'lib.python3.5.site-packages.twisted.conch.client',
              'lib.python3.5.site-packages.twisted.conch.insults', 'lib.python3.5.site-packages.twisted.conch.scripts',
              'lib.python3.5.site-packages.twisted.conch.openssh_compat', 'lib.python3.5.site-packages.twisted.names',
              'lib.python3.5.site-packages.twisted.names.test', 'lib.python3.5.site-packages.twisted.trial',
              'lib.python3.5.site-packages.twisted.trial.test', 'lib.python3.5.site-packages.twisted.words',
              'lib.python3.5.site-packages.twisted.words.im', 'lib.python3.5.site-packages.twisted.words.test',
              'lib.python3.5.site-packages.twisted.words.xish', 'lib.python3.5.site-packages.twisted.words.protocols',
              'lib.python3.5.site-packages.twisted.words.protocols.jabber',
              'lib.python3.5.site-packages.twisted.logger', 'lib.python3.5.site-packages.twisted.logger.test',
              'lib.python3.5.site-packages.twisted.python', 'lib.python3.5.site-packages.twisted.python.test',
              'lib.python3.5.site-packages.twisted.runner', 'lib.python3.5.site-packages.twisted.runner.test',
              'lib.python3.5.site-packages.twisted.spread', 'lib.python3.5.site-packages.twisted.spread.test',
              'lib.python3.5.site-packages.twisted.plugins', 'lib.python3.5.site-packages.twisted.scripts',
              'lib.python3.5.site-packages.twisted.scripts.test', 'lib.python3.5.site-packages.twisted._threads',
              'lib.python3.5.site-packages.twisted._threads.test', 'lib.python3.5.site-packages.twisted.internet',
              'lib.python3.5.site-packages.twisted.internet.test',
              'lib.python3.5.site-packages.twisted.internet.iocpreactor',
              'lib.python3.5.site-packages.twisted.persisted', 'lib.python3.5.site-packages.twisted.persisted.test',
              'lib.python3.5.site-packages.twisted.protocols', 'lib.python3.5.site-packages.twisted.protocols.test',
              'lib.python3.5.site-packages.twisted.protocols.haproxy',
              'lib.python3.5.site-packages.twisted.protocols.haproxy.test',
              'lib.python3.5.site-packages.twisted.enterprise', 'lib.python3.5.site-packages.twisted.application',
              'lib.python3.5.site-packages.twisted.application.test',
              'lib.python3.5.site-packages.twisted.application.twist',
              'lib.python3.5.site-packages.twisted.application.twist.test',
              'lib.python3.5.site-packages.twisted.application.runner',
              'lib.python3.5.site-packages.twisted.application.runner.test',
              'lib.python3.5.site-packages.twisted.positioning', 'lib.python3.5.site-packages.twisted.positioning.test',
              'lib.python3.5.site-packages.coverage', 'lib.python3.5.site-packages.dateutil',
              'lib.python3.5.site-packages.dateutil.tz', 'lib.python3.5.site-packages.dateutil.zoneinfo',
              'lib.python3.5.site-packages.queuelib', 'lib.python3.5.site-packages.queuelib.tests',
              'lib.python3.5.site-packages.requests', 'lib.python3.5.site-packages.requests.packages',
              'lib.python3.5.site-packages.requests.packages.chardet',
              'lib.python3.5.site-packages.requests.packages.urllib3',
              'lib.python3.5.site-packages.requests.packages.urllib3.util',
              'lib.python3.5.site-packages.requests.packages.urllib3.contrib',
              'lib.python3.5.site-packages.requests.packages.urllib3.packages',
              'lib.python3.5.site-packages.requests.packages.urllib3.packages.ssl_match_hostname',
              'lib.python3.5.site-packages.cssselect', 'lib.python3.5.site-packages.pycparser',
              'lib.python3.5.site-packages.pycparser.ply', 'lib.python3.5.site-packages._markerlib',
              'lib.python3.5.site-packages.constantly', 'lib.python3.5.site-packages.finsymbols',
              'lib.python3.5.site-packages.matplotlib', 'lib.python3.5.site-packages.matplotlib.tri',
              'lib.python3.5.site-packages.matplotlib.axes', 'lib.python3.5.site-packages.matplotlib.style',
              'lib.python3.5.site-packages.matplotlib.tests', 'lib.python3.5.site-packages.matplotlib.compat',
              'lib.python3.5.site-packages.matplotlib.testing',
              'lib.python3.5.site-packages.matplotlib.testing.jpl_units',
              'lib.python3.5.site-packages.matplotlib.backends',
              'lib.python3.5.site-packages.matplotlib.backends.qt_editor',
              'lib.python3.5.site-packages.matplotlib.delaunay', 'lib.python3.5.site-packages.matplotlib.externals',
              'lib.python3.5.site-packages.matplotlib.sphinxext',
              'lib.python3.5.site-packages.matplotlib.sphinxext.tests',
              'lib.python3.5.site-packages.matplotlib.projections', 'lib.python3.5.site-packages.pydispatch',
              'lib.python3.5.site-packages.pytest_cov', 'lib.python3.5.site-packages.setuptools',
              'lib.python3.5.site-packages.setuptools.command', 'lib.python3.5.site-packages.sqlalchemy',
              'lib.python3.5.site-packages.sqlalchemy.ext', 'lib.python3.5.site-packages.sqlalchemy.ext.declarative',
              'lib.python3.5.site-packages.sqlalchemy.orm', 'lib.python3.5.site-packages.sqlalchemy.sql',
              'lib.python3.5.site-packages.sqlalchemy.util', 'lib.python3.5.site-packages.sqlalchemy.event',
              'lib.python3.5.site-packages.sqlalchemy.engine', 'lib.python3.5.site-packages.sqlalchemy.testing',
              'lib.python3.5.site-packages.sqlalchemy.testing.suite',
              'lib.python3.5.site-packages.sqlalchemy.testing.plugin',
              'lib.python3.5.site-packages.sqlalchemy.dialects',
              'lib.python3.5.site-packages.sqlalchemy.dialects.mssql',
              'lib.python3.5.site-packages.sqlalchemy.dialects.mysql',
              'lib.python3.5.site-packages.sqlalchemy.dialects.oracle',
              'lib.python3.5.site-packages.sqlalchemy.dialects.sqlite',
              'lib.python3.5.site-packages.sqlalchemy.dialects.sybase',
              'lib.python3.5.site-packages.sqlalchemy.dialects.firebird',
              'lib.python3.5.site-packages.sqlalchemy.dialects.postgresql',
              'lib.python3.5.site-packages.sqlalchemy.databases', 'lib.python3.5.site-packages.sqlalchemy.connectors',
              'lib.python3.5.site-packages.incremental', 'lib.python3.5.site-packages.incremental.tests',
              'lib.python3.5.site-packages.marshmallow', 'lib.python3.5.site-packages.cryptography',
              'lib.python3.5.site-packages.cryptography.x509', 'lib.python3.5.site-packages.cryptography.hazmat',
              'lib.python3.5.site-packages.cryptography.hazmat.backends',
              'lib.python3.5.site-packages.cryptography.hazmat.backends.openssl',
              'lib.python3.5.site-packages.cryptography.hazmat.backends.commoncrypto',
              'lib.python3.5.site-packages.cryptography.hazmat.bindings',
              'lib.python3.5.site-packages.cryptography.hazmat.bindings.openssl',
              'lib.python3.5.site-packages.cryptography.hazmat.bindings.commoncrypto',
              'lib.python3.5.site-packages.cryptography.hazmat.primitives',
              'lib.python3.5.site-packages.cryptography.hazmat.primitives.kdf',
              'lib.python3.5.site-packages.cryptography.hazmat.primitives.ciphers',
              'lib.python3.5.site-packages.cryptography.hazmat.primitives.twofactor',
              'lib.python3.5.site-packages.cryptography.hazmat.primitives.asymmetric',
              'lib.python3.5.site-packages.cryptography.hazmat.primitives.interfaces',
              'lib.python3.5.site-packages.mpl_toolkits.tests', 'lib.python3.5.site-packages.mpl_toolkits.mplot3d',
              'lib.python3.5.site-packages.mpl_toolkits.axes_grid',
              'lib.python3.5.site-packages.mpl_toolkits.axes_grid1',
              'lib.python3.5.site-packages.mpl_toolkits.axisartist', 'lib.python3.5.site-packages.pkg_resources',
              'lib.python3.5.site-packages.pkg_resources._vendor',
              'lib.python3.5.site-packages.pkg_resources._vendor.packaging',
              'lib.python3.5.site-packages.pyasn1_modules', 'lib.python3.5.site-packages.service_identity',
              'lib.python3.5.site-packages.pandas_datareader', 'lib.python3.5.site-packages.pandas_datareader.io',
              'lib.python3.5.site-packages.pandas_datareader.io.tests',
              'lib.python3.5.site-packages.pandas_datareader.yahoo',
              'lib.python3.5.site-packages.pandas_datareader.google', 'test', 'pytech', 'crawler', 'crawler.spiders'],
    url='https://github.com/kprestel/PyTech',
    license='JSON',
    author='Kyle Prestel',
    author_email='kprestel@gmail.com',
    description='A Python Library for doing technical and fundament asset analysis'
)
